language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - travis_retry sudo apt-get update

install:
  - travis_retry sudo apt-get install memcached
  - git submodule init
  - git submodule update
  - memcached -h | head -1

script: make && make test

